# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts a 2D tangentspace vector representation to 3D
#'
#' @param x vetor length 3
#' @param a vetor length 2
#' @return vector length 3
get_v_rcpp <- function(x, a) {
    .Call(`_spheregr_get_v_rcpp`, x, a)
}

#' Convert angle representation to R3.
#'
#' @param x vetor length 2
#' @return vector length 3
angle2R3_1 <- function(x) {
    .Call(`_spheregr_angle2R3_1`, x)
}

